name: "🚀 Improvement Request"
description: Suggest an improvement to the documentation.
labels: ["Type/Improvement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the current limitation or any unclear content in the documentation.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you suggest.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version(s)
      description: Provide all the applicable documentation versions that this improvement is expected to be included.
      placeholder: 4.5.0, 4.4.0, 4.3.0
    validations:
      required: true
